---
title: HOME
description: Welcome to this sample project
images: ["/images/sample.jpg"]
---

**Welcome to my personal website,**

I created this website to get people to know my work, to share some of my knowledge in computational finance and to create tools that people may find useful for their personal finance and their jobs. I will do my best to have some practical gadgets up to date at the home page. Anyway, you can find my posts in the blog section, where I will be solving interesting problems and replicating research papers main results. Do not forget to follow me on Twitter.

*The opinions expressed in this website represent my own and not those of my employer.* 

[Get to know me better](/resume "Get to know me better")

My dad dead recently and I want to honor him in my website by making public the speech I gave at his funeral. 

**El dios abandona a Antonio**

Cuando de repente, a medianoche, se escuche
pasar una comparsa invisible
con músicas maravillosas, con vocerío;
tu suerte que ya declina, tus obras
que fracasaron, los planes de tu vida
que resultaron todos ilusiones, no llores inútilmente.
Como preparado desde tiempo atrás, como valiente,
di adiós a Alejandría que se aleja.
Sobre todo no te engañes, no digas que fue un
sueño, que se engañó tu oído:
no aceptes tales vanas esperanzas.
Como preparado desde tiempo atrás, como valiente,
como te corresponde a ti que de tal ciudad fuiste digno,
acércate resueltamente a la ventana,
y escucha con emoción, mas no
con los ruegos y lamentos de los cobardes,
como último placer los sones,
los maravillosos instrumentos del cortejo misterioso,
y dile adiós a la Alejandría que pierdes.

-	*Constantino Cavafis*

**Nihil Sub Sole Novum**

Malogrados quienes no siguen el camino del hombre digno. No jueguen a la víctima si les diagnostican una enfermedad terminal. No sientan autocompasión por su malestar ni culpen a quienes los rodean de sus penas y sus desventuras. Son cómplices y no mártires de su infortunio, quienes imputan culpas y responsabilidades a sus allegados, sobre acontecimientos propios de la naturaleza, frutos del caos y del azar. La estética del hombre estoico radica en empatar con el azar, en no renegar ante la incertidumbre y controlar solo aquello que está a su alcance. La valentía del héroe está en levantarse y aceptar su deceso con honor. El hombre es digno cuando No se somete a su destino y es elegante cuando ve la normalidad tanto en el fracaso como en la muerte y la enfermedad. 

En su lecho de muerte, Jorge Humberto empató con el azar. Resultado de lo incontrolable, acarreó una enfermedad terminal con dolores tan traumáticos que lo desarmaban físicamente ante su destino. No obstante, rememorando el coraje de Marco Antonio al ser traicionado por su dios y morir en las manos de Octavio, sobrellevó su enfermedad con valentía y con honor, sin ruegos irresolutos ni lamentos cobardes. Un hombre estoico. Un hombre digno que no reprochó de su malestar y aceptó su infortunio con elegancia: “lo recibo como un regalo [cito sus palabras]. Para mí, realmente, es una parte de la vida, la muerte. Para mí, es ser absorbido por el universo de nuevo”.

Mi papá será recordado como el calasancio, el seminarista, el filósofo, el revolucionario, el vendedor, el empresario, el padre de familia, el esposo, el abuelo, el poeta, el escritor y como un gran amigo. En sus largos años logró muchos recuerdos en sus allegados, larga vida espera a quien de casta bravía recorre los Andes con atrevimiento y sagacidad. Sin embargo, si algo demostró con creces fue su valentía. 14 meses de sufrimiento no derrumbaron su personalidad estoica y logró, con el último aliento de fuerza que le quedaba, estirar sus brazos para despedirse de quien más amaba con un ligero apretón de manos que pretendía ser un abrazo. Jorge Humberto aceptó la enfermedad con coraje, padeció dolores inmensurables dignamente y recibió la muerte con elegancia.

