---
title: Tools
description: Useful tools for asset allocation
images: ["/images/sample.jpg"]
---

Disclaimer: Any information provided here do not constitute any kind of financial/investment advice. Instead, everything on this website constitutes nothing else than an exercise for academic purposes.

### Long Trading European Options

If you feel like trading options this Excel template is perfect for you. It allows you to price European stock options and analyze their inherent risks based on the famous Black-Scholes-Merton model, the Greek letters and the volatility smile; using real time data from [Yahoo Finance](https://finance.yahoo.com/). This template use Power Query to connect and transform market data, and VBA to run all financial modeling. On its five different sections, you will be able to assess thoroughly any potential or actual position on the market.

#### Prerequisites

(i) European style options general knowledge.

(ii) Turn on Microsoft VBScript Regular Expressions 5.5.

  - Go to developer tab and open Visual Basic
  - Hit on *Tools/Reference -> Microsoft VBScript Regular Expressions 5.5 -> OK*


#### How to use it?

This template is connected to [Yahoo Finance](https://finance.yahoo.com/), which makes it easy to analyze any stock option with real time data. Therefore, you only need to know three things:

1. If you don't want to analyze the ticket selected by default (ARI), go to *Data -> Queries & Connections -> Symbol (ARI)* and right-click on it. Select *Edit*, write the symbol of the underlying stock of the option you want to analyze and hit *Close & Load Data*. Finally hit on the *Refresh All* button in the Data tab. Don't worry if the Greeks section throws error messages. This is because the new data may not make sense for the options settled for analysis. This problem should be fixed after the second step.

2. In the section **POTENTIAL (OR ACTUAL) TRADE**, input the specifics of your current trade or potential trade that you are trying to analyze.

3. The data will update automatically every 15 minutes; however, you can always update by hitting on the *Refresh All* button in the Data tab. 

#### Download

[Click here](/Excel/OptionsAnalysis.xlsm) to download the last version of the template.

