---
title: Tools
description: Useful tools for asset allocation
images: ["/images/sample.jpg"]
---

Disclaimer: Any information provided here do not constitute any kind of financial/investment advice. Instead, everything on this website constitutes nothing else than an exercise for academic purposes.

### Long Trading European Options

If you feel like trading options this Excel template is perfect for you. It allows you to price European stock options and analyze their inherent risks based on the famous Black-Scholes-Merton model, the Greek letters and the volatility smile; using real time data from [Yahoo Finance](https://finance.yahoo.com/). This template uses Power Query to connect and transform market data, and VBA to run all financial modeling. On its five different sections, you will be able to assess thoroughly any potential or actual position on the market.

#### Prerequisites

(i) European style options general knowledge.

(ii) Turn on Microsoft VBScript Regular Expressions 5.5.

  - Go to developer tab and open Visual Basic
  - Hit on *Tools/Reference -> Microsoft VBScript Regular Expressions 5.5 -> OK*


#### How to use it?

This template is connected to [Yahoo Finance](https://finance.yahoo.com/), which makes it easy to analyze any stock option with real time data. Therefore, you only need to know three things:

1. If you don't want to analyze the ticket selected by default (ARI), go to *Data -> Queries & Connections -> Symbol (ARI)* and right-click on it. Select *Edit*, write the symbol of the underlying stock of the option you want to analyze and hit *Close & Load Data*. Finally hit on the *Refresh All* button in the Data tab. Don't worry if the Greeks section throws error messages. This is because the new data may not make sense for the options settled for analysis. This problem should be fixed after the second step.

2. In the section **POTENTIAL (OR ACTUAL) TRADE**, input the specifics of your current trade or potential trade that you are trying to analyze.

3. The data will update automatically every 15 minutes; however, you can always update by hitting on the *Refresh All* button in the Data tab. 

#### Download

[Click here](/Excel/OptionsAnalysis.xlsm) to download the last version of the template.

### Personal Finance Tracker

If you are the kind of person who likes to manage your personal finance in much detail as possible, and if you also feel passionate for Accounting and Financial Analysis, this template is made for you. You will be able to build your own ledger and track your finances with all of the detail you want, relying on the most important financial statements and three dashboards to analyze you financial status: one for liquidity, other for indebtedness and a last one to assess the profitability of your savings.If you have problems dealing with this template feel free to contact me.  

#### Prerequisites

(i) Account principles understanding.

(ii) A little bit of Financial Analysis.

#### How to use it?

Basically you need to do two things: keep you ledger and your investments up to date.

1. To keep your ledger up to date hit one the *Ledger* button and input your numbers following the basic accounting principles for debits and credits.

2. Hit on *NAV* and update your position on all of the funds you list on the Funds tab. Notice that market data is stored on tabs **LVA** and **Colcap** from files downloaded from [SIFI Colombia](https://sificcolombia.lvaindices.com/estadisticas/) and [BanRep](https://www.banrep.gov.co/es/estadisticas/mercado-accionario), respectively. You need to keep these files updated too. If you are not from Colombia you may want to change the source for another one with the same columns.

#### Download

[Click here](/Excel/PersonalFinance.xlsm) to download the last version of the template.

